// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUAFOrvA_Op-qfJUAWM9Feq0KOK06Nvy4',
    appId: '1:477790334346:web:49509c532ab3f2a0d06c73',
    messagingSenderId: '477790334346',
    projectId: 'e-commerce-system-4fc03',
    authDomain: 'e-commerce-system-4fc03.firebaseapp.com',
    storageBucket: 'e-commerce-system-4fc03.appspot.com',
    measurementId: 'G-YYLNBZWJXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRbUzJ_3xnuxA5IdVeRvdaGIXSk894Io',
    appId: '1:477790334346:android:9bcfbb13dc1c8b22d06c73',
    messagingSenderId: '477790334346',
    projectId: 'e-commerce-system-4fc03',
    storageBucket: 'e-commerce-system-4fc03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDngzAU2dPRew4HHXzqoTz4ILTBjscbOtE',
    appId: '1:477790334346:ios:9dada5a60a159251d06c73',
    messagingSenderId: '477790334346',
    projectId: 'e-commerce-system-4fc03',
    storageBucket: 'e-commerce-system-4fc03.appspot.com',
    iosBundleId: 'com.example.eCommerceAdminPanel',
  );
}
